name: Sync with Upstream
on:
  schedule:
    - cron: '0 0 * * *' # 每天0点自动执行
  workflow_dispatch: # 允许手动触发
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 关键步骤：先检出下游仓库代码，建立Git环境（必须放在repo-sync之前）
      - name: Checkout Downstream Repository
        uses: actions/checkout@v4
        with:
          ref: main # 检出下游目标分支（需与后续destination_branch一致）
          fetch-depth: 0 # 拉取完整的Git历史，确保合并时无缺失

      # 同步上游仓库（此时已存在Git环境，不会报错）
      - name: Sync Upstream to Downstream
        uses: repo-sync/github-sync@v2.0.0
        with:
          source_repo: '7Sageer/sublink-worker' # 上游仓库（用户名/仓库名）
          source_branch: 'main' # 上游分支
          destination_branch: 'main' # 下游目标分支（与checkout的ref一致）
          github_token: ${{ secrets.GITHUB_TOKEN }} # 内置Token
          args: '--merge-strategy theirs' # 冲突时保留上游（覆盖下游）
